### ISSUE TITLE
Map Positioning and Tile Update

### ISSUE THREAD

**Issue by ted-dunstone** [Bunkerbewohner/threejs-hex-map#1]
Thanks for a very interesting project. I've enjoyed getting familiar with TypeScript.

I have two questions:
- I have implemented a simple zoom function - but can't find a way to scroll the map to a specific coordinate.
- If I change a tile (or tile property on the map - e.g. to add tree's) how do I force it to refresh the map (currently the map doesn't update even after calling mapView.updateTiles(updated));

Cheers.

**Comment by Bunkerbewohner** [comment]
Hi, thanks for checking it out!

I just added a new method to MapView called "focus(q,r)" that will focus a specific QR coordinate (centering it in the view). I also adjusted MapView.setZoom to keep the same "view center" when changing the zoom. 

Have a look at MapView.getCameraFocusPositionWorld(v) which you could use to compute the new camera position based on where you want the camera to focus. Then for a panning animation you could just tween between the current camera position and the result of getCameraFocusPositionWorld.

As for updating tiles: Currently only the fog of war is updated, yes. I just haven't gotten around to implementing other updates because that requires shifting or adding vertices within vertex buffers. Essentially right now you would need to recreate the entire map. 

To implement this (which I'm going to do soon because I need it myself) the vertex attributes need to be dynamically resized when trees or mountains are added after the fact. For this the underlying Float32Arrays need to be resized.

**Comment by ted-dunstone** [comment]
That's great. Thanks for the reply. I'm looking forward to seeing where you take this project. Perhaps you could add a quick roadmap description of the features you are thinking of adding (may help avoid duplication by others). Cheers and happy new year

**Comment by Bunkerbewohner** [comment]
A road map is a good idea, thanks. Happy New Year to you, too!
